[env:esp32dev]
platform = espressif32@5.3.0 
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  claws/BH1750
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  nuviot
  adafruit/Adafruit Unified Sensor
  adafruit/DHT sensor library
  milesburton/DallasTemperature
  https://github.com/PaulStoffregen/OneWire.git
  https://github.com/WifWaf/MH-Z19.git
  adafruit/Adafruit BME680 Library
  sparkfun/SparkFun Soil Moisture Sensor
